name: run mkarchiso

# on:
#   workflow_dispatch: {}
on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: cleanup work dir
        run: | 
          if [[ -d work ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf work/
          fi
          if [[ -d out ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf out/
          fi
          
      - uses: actions/checkout@v3
          
      # - name: add ironrobin public key iff n
      #   run: |
      #     echo ${{ secrets.SUDO_PASSWD }} | sudo pacman-key --recv-keys 6ED02751500A833A --keyserver pgp.mit.edu
      #     echo ${{ secrets.SUDO_PASSWD }} | sudo pacman-key --lsign-key 6ED02751500A833A
          
      - name: build the ISO
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S ./archiso/mkarchiso -v configs/x13s
          
      - name: deploy iso to static file server
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S chown -R alex:alex out/
          scp out/* rockpro64:/srv/static/
