name: run mkarchiso

on:
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: cleanup work dir
        run: | 
          if [[ -d work ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf work/
          fi
          if [[ -d out ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf out/
          fi
          
      - uses: actions/checkout@v3
          
      - name: download leo x13s repo pubkey
        run: |
          wget https://lecs.dev/repo/public.asc
          pacman-key --add public.asc
          pacman-key --lsign 9FD0B48BBBD974B80A3310AB6462EE0B8E382F3F
          
      - name: build the ISO
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S ./archiso/mkarchiso -v configs/x13s
          
      - name: deploy iso to static file server
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S chown -R alex:alex out/
          scp out/* rockpro64:/srv/static/
