name: run mkarchiso

on:
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: cleanup work dir
        run: | 
          if [[ -d work ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf work/
          fi
          if [[ -d out ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf out/
          fi
          
      - uses: actions/checkout@v3
          
      - name: download patched kernel
        run: |
          scp rockpro64:/srv/static/linux-x13s-*.tar.xz .
          
      - name: create custom package repository containing patched kernel
        run: |
          mkdir -p local/repo
          cp linux-x13s-*.tar.xz local/repo
          repo-add local/repo/custom.db.tar.gz linux-x13s-*.tar.xz
          
      - name: build the ISO
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S ./archiso/mkarchiso -v configs/releng
          
      - name: deploy iso to static file server
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S chown -R alex:alex out/
          scp out/* rockpro64:/srv/static/
