name: run mkarchiso

on:
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: cleanup work dir
        run: | 
          pwd
          [[ -d work ]] && echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf work/
          [[ -d out ]]  && echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf out/
    
      - uses: actions/checkout@v3
      
      - name: build the ISO
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S ./archiso/mkarchiso -v configs/releng
