name: Build archiso-x13s
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: cleanup work dir
      run: |
        echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf $PWD
        mkdir -p $PWD
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: build archiso
      run: |
        docker run -t -v $PWD:/build menci/archlinuxarm /bin/bash /build/entrypoint.sh
        ls -l .

